# docker-compose.yaml
#
# Aternity Tech-Community
# 107-opentelemetry-autoinstrumentation-nodejs-app
# version: 22.11.221128
#
# Compose file to use with the cookbook 107
#
# Usage
#   docker-compose up
#
# Example in Bash
#   export ATERNITY_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   export ATERNITY_CUSTOMER_ID="12341234-12341234-13241234"
#   docker-compose up
#
# Example in PowerShell
#   $env:ATERNITY_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   $env:ATERNITY_CUSTOMER_ID="12341234-12341234-13241234"
#   docker-compose up

version: "3.9"

services:

  aternity-opentelemetry-collector:

    # Aternity OpenTelemetry Collector
    # https://hub.docker.com/r/aternity/apm-collector

    image: registry.hub.docker.com/aternity/apm-collector:2022.4.0-4

    environment:
    
      SERVER_URL: "wss://${ATERNITY_SAAS_SERVER_HOST}/?RPM_AGENT_CUSTOMER_ID=${ATERNITY_CUSTOMER_ID}"
    
    ports:

      # OpenTelemetry, https://opentelemetry.io

      - "4318:4318/tcp"   # OpenTelemetry OTLP JSON/Protobuf over HTTP
      - "55681:55681/tcp" # OpenTelemetry OTLP JSON/Protobuf over HTTP
      - "4317:4317/tcp"   # OpenTelemetry OTLP over gRPC

      # Uncomment the line to expose the endpoints for other telemetry protocols
      #          
      # Zipkin, https://zipkin.io
      # - "9411:9411/tcp"   # Zipkin v2 json/protobuf and v1 json/thrift
      # - "5775:5775/udp"   # Jaeger's Thrift support for Zipkin v1
      #
      # Jaeger, https://www.jaegertracing.io
      # - "14268:14268/tcp" # Jaeger Thrift Binary over HTTP
      # - "6831:6831/udp"   # Jaeger Thrift Compact
      # - "6832:6832/udp"   # Jaeger Thrift Binary

  service107_js:   
    
    environment:  
    
      OTEL_SERVICE_NAME: service107_js
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aternity-opentelemetry-collector:4317

    ports:
      - "8107:80"

    build:
      context: https://github.com/Aternity/Tech-Community.git#main
      dockerfile: 107-opentelemetry-autoinstrumentation-nodejs-app/Dockerfile
