# Aternity Tech-Community
# 105-opentelemetry-go-app

# Exporter
EXPORTER: otlp

# Jaeger endpoint
JAEGER_PORT: 14268
JAEGER_PATH: /api/traces

# Zipkin endpoint
ZIPKIN_PORT: 9411
ZIPKIN_PATH: /api/v2/spans

# OTLP endpoint
OTLP_PORT: 4318
OTLP_PATH: /v1/traces

# Aternity APM collector configuration
ATERNITY_COLLECTOR_SERVICE_HOST: localhost

# Server configurations
FRONTEND_SERVICE_HOST: localhost
FRONTEND_SERVICE_PORT: 8081
BACKEND_SERVICE_HOST: localhost
BACKEND_SERVICE_PORT: 9000

# Sleep millis
SLEEP: 5
