steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_APM_PACKAGE_GSUTIL_URI}', './aternity-apm-jida-linux.zip']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/cookbook-233', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/cookbook-233']
substitutions:
  _APM_PACKAGE_GSUTIL_URI: gs://my_bucket/aternity-apm-jida-linux-12.18.0_BL546.zip
  _REGION: europe-west9
  _REPOSITORY: aternity-apm
  _IMAGE_NAME: cookbook-233