# Aternity Tech-Community
# 105-opentelemetry-go-app
# version: 22.06.03
#
# Simple 2 tier Go application using the OpenTelemetry SDK. Capable of showing distributed traces
# using the Otlp, Jaeger, or Zipkin formats.
#
# Reference:
# * https://hub.docker.com/r/aternity/apm-collector
# * https://www.aternity.com/application-performance-monitoring
#
# Usage:
#   docker-compose up
#
# Example in Unix
#   ATERNITY_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com" ATERNITY_CUSTOMER_ID="12341234-12341234-13241234" docker-compose up
#
# Example PowerShell
#   $env:ATERNITY_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   $env:ATERNITY_CUSTOMER_ID="ATERNITY_CUSTOMER_ID="12341234-12341234-13241234"
#   docker-compose up

version: '3.8'

services:

  aternity-collector:
    image: aternity/apm-collector:latest
    container_name: aternity-collector
    environment:
      - SERVER_URL=wss://${ATERNITY_SAAS_SERVER_HOST}/?RPM_AGENT_CUSTOMER_ID=${ATERNITY_CUSTOMER_ID}

  service105-go-backend:
    depends_on:
      - aternity-collector
    command: backend
    container_name: opentelemetry-go-backend
    environment:
      OTEL_SERVICE_NAME: service105-go-backend
      OTEL_TRACES_EXPORTER: otlp  # otlp, jaeger, zipkin, file
      ADD_CONSOLE_EXPORTER: "off" # "on", "off"
      ATERNITY_COLLECTOR_SERVICE_HOST: aternity-collector
    build:
      context: .
      dockerfile: Dockerfile

  service105-go-frontend:
    depends_on:
      - service105-go-backend
    command: frontend
    container_name: opentelemetry-go-frontend
    environment:
      OTEL_SERVICE_NAME: service105-go-frontend
      OTEL_TRACES_EXPORTER: otlp  # otlp, jaeger, zipkin, file
      ADD_CONSOLE_EXPORTER: "off" # "on", "off"
      ATERNITY_COLLECTOR_SERVICE_HOST: aternity-collector
      BACKEND_SERVICE_HOST: opentelemetry-go-backend
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: Dockerfile

  service105-traffic-generator:
    depends_on:
      - service105-go-frontend
    image: alpine/curl:latest
    container_name: traffic-generator
    command: >
      /bin/sh -c "
        sleep 5;
        while :; do
          curl http://opentelemetry-go-frontend:8081/ > /dev/null 2>&1;
          sleep 5;
        done
      "
