# docker-compose.yaml
# version: 23.1.22
# Cookbook 203 - Aternity Tech Community Cookbook (https://github.com/Aternity/Tech-Community)
#
# Usage:
#
#   docker-compose up
#
# Example with Bash:
#
#   export ALLUVIO_ATERNITY_APM_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   export ALLUVIO_ATERNITY_APM_CUSTOMER_ID="12341234-12341234-13241234"
#   docker-compose up
#
# Example PowerShell
#
#   $env:ALLUVIO_ATERNITY_APM_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   $env:ALLUVIO_ATERNITY_APM_CUSTOMER_ID="12341234-12341234-13241234"
#   docker-compose up

version: "3.9"

services:

  demo-app-apm:

    environment:
    - ALLUVIO_ATERNITY_APM_SAAS_SERVER_HOST
    - ALLUVIO_ATERNITY_APM_CUSTOMER_ID
    - RVBD_APP_INSTANCE=cookbook-203

    build:
      context: .
      dockerfile: Dockerfile

    ports:
    - "8080:8080/tcp"
