# docker-compose.yaml
#
# Aternity Tech-Community
# 109-opentelemetry-collector
# version: 22.3.1
#
# ref:
# * https://github.com/open-telemetry/opentelemetry-go/tree/main/example/otel-collector

version: "3.8"

services:

  aternity-opentelemetry-collector:

    # Aternity OpenTelemetry Collector
    # https://hub.docker.com/r/aternity/apm-collector

    image: registry.hub.docker.com/aternity/apm-collector:2022.3.0-3

    container_name: aternity-opentelemetry-collector

    environment:
    
      SERVER_URL: "wss://${ATERNITY_SAAS_SERVER_HOST}/?RPM_AGENT_CUSTOMER_ID=${ATERNITY_CUSTOMER_ID}"
    
    ports:

      # Uncomment the telemetry protocol used by the application

      # OpenTelemetry, https://opentelemetry.io
      - "4318:4318/tcp"     # OpenTelemetry OTLP JSON/Protobuf over HTTP
      # - "55681:55681/tcp" # OpenTelemetry OTLP JSON/Protobuf over HTTP
      # - "4317:4317/tcp"   # OpenTelemetry OTLP over gRPC
      
      # Jaeger, https://www.jaegertracing.io
      # - "14268:14268/tcp" # Jaeger Thrift Binary over HTTP
      # - "6831:6831/udp"   # Jaeger Thrift Compact
      # - "6832:6832/udp"   # Jaeger Thrift Binary
      
      # Zipkin, https://zipkin.io
      # - "9411:9411/tcp"   # Zipkin v2 json/protobuf and v1 json/thrift
      # - "5775:5775/udp"   # Jaeger's Thrift support for Zipkin v1

  example-app:
    build:
      # Local context
      dockerfile: Dockerfile
      context: .
      # TODO: remote context
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - otel-collector

  otel-collector:

    # OpenTelemetry Collector
    # https://github.com/open-telemetry

    image: registry.hub.docker.com/otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317"        # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - aternity-opentelemetry-collector

  jaeger-all-in-one:

    # Jaeger
    # UI: http://localhost:16686
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # frontend
      - "14268"       # jaeger.thrift
      - "14250"       # model.proto

  zipkin-all-in-one:

    # Zipkin
    # UI: http://localhost:9411/zipkin
    container_name: zipkin-all-in-one
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"